Vagrant.configure("2") do |config|
  config.vm.define "ubu14" do |ubu14|
    ubu14.vm.box = "ubuntu/trusty64"
    ubu14.vm.hostname = 'ubu14'

    ubu14.vm.network :public_network, ip: "192.168.1.22"
    ubu14.vm.network :forwarded_port, guest: 22, host: 10122, id: "ssh"
    ubu14.vm.provision :ansible do |ansible|
            ansible.playbook = "test.yml"
    end

  end

  config.vm.define "ubu16" do |ubu16|
   ubu16.vm.box = "puphpet/ubuntu1604-x64"
   ubu16.vm.hostname = 'ubu16'

    ubu16.vm.network :public_network, ip: "192.168.1.23"
    ubu16.vm.network :forwarded_port, guest: 22, host: 10222, id: "ssh"
    ubu16.vm.provision :ansible do |ansible|
            ansible.playbook = "test.yml"
    end
  end
  config.vm.define "deb" do |deb|
   deb.vm.box = "debian/jessie64"
   deb.vm.hostname = 'deb'

    deb.vm.network :public_network, ip: "192.168.1.24"
    deb.vm.network :forwarded_port, guest: 22, host: 10322, id: "ssh"
    deb.vm.provision :ansible do |ansible|
            ansible.playbook = "test.yml"
    end
  end
  config.vm.define "cent" do |cent|
   cent.vm.box = "centos/7"
   cent.vm.hostname = 'cent'

    cent.vm.network :public_network, ip: "192.168.1.25"
    cent.vm.network :forwarded_port, guest: 22, host: 10422, id: "ssh"
    cent.vm.provision :ansible do |ansible|
            ansible.playbook = "test.yml"
    end
  end
end
