Vagrant.configure("2") do |config|
  config.vm.define "ubu14" do |ubu14|
    ubu14.vm.box = "ubuntu/trusty64"
    ubu14.vm.hostname = 'ubu14'

    ubu14.vm.network :public_network, ip: "192.168.1.22"
    ubu14.vm.network :forwarded_port, guest: 22, host: 10122, id: "ssh"
    ubu14.vm.provision :ansible do |ansible|
            ansible.playbook = "test.yml"
    end

  end

  config.vm.define "ubu16" do |ubu16|
   ubu16.vm.box = "puphpet/ubuntu1604-x64"
   ubu16.vm.hostname = 'ubu16'

    ubu16.vm.network :public_network, ip: "192.168.1.23"
    ubu16.vm.network :forwarded_port, guest: 22, host: 10222, id: "ssh"
    ubu16.vm.provision :ansible do |ansible|
            ansible.playbook = "test.yml"
    end
  end
  config.vm.define "deb8" do |deb8|
   deb8.vm.box = "debian/jessie64"
   deb8.vm.hostname = 'deb8'

    deb8.vm.network :public_network, ip: "192.168.1.24"
    deb8.vm.network :forwarded_port, guest: 22, host: 10322, id: "ssh"
    deb8.vm.provision :ansible do |ansible|
            ansible.playbook = "test.yml"
    end
  end
  config.vm.define "deb9" do |deb9|
   deb9.vm.box = "debian/stretch64"
   deb9.vm.hostname = 'deb9'

    deb9.vm.network :public_network, ip: "192.168.1.25"
    deb9.vm.network :forwarded_port, guest: 22, host: 10422, id: "ssh"
    deb9.vm.provision :ansible do |ansible|
            ansible.playbook = "test.yml"
    end
  end
  config.vm.define "cent" do |cent|
   cent.vm.box = "centos/7"
   cent.vm.hostname = 'cent'

    cent.vm.network :public_network, ip: "192.168.1.26"
    cent.vm.network :forwarded_port, guest: 22, host: 10522, id: "ssh"
    cent.vm.provision :ansible do |ansible|
            ansible.playbook = "test.yml"
    end
  end
end
